apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pilot_role-bind-pilot_account

subjects:
  - kind: ServiceAccount
    namespace: pilot-namespace
    name: pilot-account

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pilot-role
  