apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pilot-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods","pods/log","pods/exec", "pods/attach", "pods/status","services" ]
    verbs: [ "get", "watch", "list", "create", "update", "patch", "delete" ]
  