apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: admission-demo-ns
  labels:
    app: admisson-bysvc
  name: admisson-bysvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admisson-bysvc
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: admisson-bysvc
    spec:
      containers:
        - image: pod-demo-admission-controller
          name: pod-demo-admission-controller
          resources: { }
          command: [ "/PodDemoLabelAdmissionController" ]
