apiVersion: v1
kind: Service
metadata:
  namespace: admission-demo-ns
  labels:
    app: mutating-svc
  name: mutating-svc
spec:
  ports:
    - port: 10801
      protocol: TCP
      targetPort: 10801
  selector:
    app: admisson-bysvc
  type: ClusterIP
status:
  loadBalancer: { }
  