apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "pod-demo-label-mutating-bysvc"
webhooks:
  - name: "pod-demo-label-mutating"
    rules:
      - apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE" ]
        resources: [ "pods" ]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: admission-demo-ns
        name: mutating-svc
        path: /mutating-bysvc
        port: 10801
    admissionReviewVersions: [ "v1" ]
    timeoutSeconds: 5
