apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello
spec:
  containers:
    - name: hello
      image: local/hello:alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3000
    - name: hello
      image: local/hello:alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3001
    - name: envoy
      image: local/envoy:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  initContainers:
    - name: init-container
      image: local/init:latest
      env:
        - name: APP_PORT
          value: "3000 3001"
